apiVersion: kse.scene/v0.2
kind: scene
metadata:
  obj_id: scene.erp.67-00-scene-package-contract-declaration
  obj_version: 0.2.0
  title: Scene Package Contract Declaration
spec:
  domain: erp
  intent:
    goal: Declare scene package contract metadata for template reuse and compatibility validation
  model_scope:
    read:
      - moqui.OrderHeader.orderId
      - moqui.OrderHeader.statusId
    write: []
  capability_contract:
    bindings:
      - type: query
        ref: spec.erp.scene-package-metadata-query
        timeout_ms: 2000
        retry: 0
  governance_contract:
    risk_level: low
    approval:
      required: false
    idempotency:
      required: true
      key: packageCoordinate
