apiVersion: kse.scene/v0.2
kind: scene
metadata:
  obj_id: scene.erp.68-00-scene-package-template-publish-and-instantiate
  obj_version: 0.2.0
  title: Scene Package Template Publish and Instantiate
spec:
  domain: erp
  intent:
    goal: Build publish and instantiate closure for scene package templates
  model_scope:
    read:
      - moqui.Enumeration.enumId
      - moqui.Enumeration.description
    write:
      - kse.SceneTemplate.templateId
      - kse.SceneTemplateInstance.targetSpec
  capability_contract:
    bindings:
      - type: query
        ref: spec.erp.scene-package-template.query
        timeout_ms: 2000
        retry: 0
      - type: command
        ref: spec.erp.scene-package-template.instantiate
        timeout_ms: 3000
        retry: 0
  governance_contract:
    risk_level: low
    approval:
      required: false
    idempotency:
      required: true
      key: templateInstantiateRequestId
