apiVersion: kse.scene/v0.2
kind: scene
metadata:
  obj_id: scene.erp.inventory-reserve-adjust
  obj_version: 0.1.0
  title: ERP Inventory Reserve Adjust
spec:
  domain: erp
  intent:
    goal: Execute inventory reserve and adjustment with auditable decision flow
  model_scope:
    read:
      - spec.erp.inventory-availability-query
      - spec.erp.inventory-reservation-audit
    write:
      - spec.erp.inventory-reserve
      - spec.erp.inventory-adjust
  capability_contract:
    bindings:
      - type: query
        ref: spec.erp.inventory-availability-query
        intent: Read current ATP and stock balances
        preconditions:
          - product and facility identifiers are provided
        postconditions:
          - availability snapshot is returned
        timeout_ms: 1500
        retry: 1
      - type: invoke
        ref: spec.erp.inventory-reserve
        depends_on: spec.erp.inventory-availability-query
        intent: Reserve inventory when availability is sufficient
        preconditions:
          - availability snapshot is returned
        postconditions:
          - reservation decision and record are produced
        timeout_ms: 2200
        retry: 2
      - type: invoke
        ref: spec.erp.inventory-adjust
        depends_on: spec.erp.inventory-reserve
        intent: Apply inventory adjustment when reserve outcome requires correction
        preconditions:
          - reservation decision and record are produced
        postconditions:
          - inventory adjustment record is captured
        timeout_ms: 2200
        retry: 2
      - type: query
        ref: spec.erp.inventory-reservation-audit
        depends_on: spec.erp.inventory-adjust
        intent: Audit reserve and adjustment outcome for downstream traceability
        preconditions:
          - inventory adjustment record is captured
        postconditions:
          - inventory operation audit projection is generated
        timeout_ms: 1500
        retry: 1
  governance_contract:
    risk_level: medium
    approval:
      required: true
    idempotency:
      required: true
      key: inventoryOperationId
    data_lineage:
      sources:
        - ref: spec.erp.inventory-availability-query
          fields:
            - productId
            - facilityId
            - atp
            - qoh
      transforms:
        - operation: decideReserveOrAdjust
          description: Evaluate availability and choose reserve-only or reserve-plus-adjust path.
        - operation: buildInventoryAuditProjection
          description: Compose audit projection with reserve and adjustment records.
      sinks:
        - ref: spec.erp.inventory-reservation-audit
          fields:
            - inventoryOperationId
            - reserveStatus
            - adjustmentStatus
