apiVersion: kse.scene/v0.2
kind: scene
metadata:
  obj_id: scene.erp.67-00-scene-package-contract-declaration
  obj_version: 0.2.0
  title: Scene Package Contract Declaration
spec:
  domain: erp
  intent:
    goal: Declare scene package contract metadata for template reuse and compatibility validation
  model_scope:
    read:
      - spec.erp.scene-package-contract-read
      - spec.erp.scene-package-compatibility-check
      - spec.erp.scene-package-metadata-query
    write: []
  capability_contract:
    bindings:
      - type: query
        ref: spec.erp.scene-package-contract-read
        intent: Read package contract metadata and normalize package coordinate input
        preconditions:
          - package coordinate is provided
          - caller has profile:erp read permission
        postconditions:
          - metadata fields are loaded
          - coordinate is normalized
        timeout_ms: 1500
        retry: 0
      - type: query
        ref: spec.erp.scene-package-compatibility-check
        depends_on: spec.erp.scene-package-contract-read
        intent: Evaluate kse and scene API compatibility against policy baseline
        preconditions:
          - contract metadata is loaded
          - target runtime policy is available
        postconditions:
          - compatibility status is produced
          - incompatible constraints are explained
        timeout_ms: 1500
        retry: 1
      - type: query
        ref: spec.erp.scene-package-metadata-query
        depends_on: spec.erp.scene-package-compatibility-check
        intent: Build consolidated package metadata view for publishing and routing
        preconditions:
          - compatibility status is available
        postconditions:
          - metadata view includes governance and compatibility dimensions
        timeout_ms: 2000
        retry: 1
  governance_contract:
    risk_level: low
    approval:
      required: false
    idempotency:
      required: true
      key: packageCoordinate
    data_lineage:
      sources:
        - ref: spec.erp.scene-package-contract-read
          fields:
            - group
            - name
            - version
      transforms:
        - operation: normalizePackageCoordinate
          description: Normalize group/name/version into package coordinate.
        - operation: evaluateCompatibilityPolicy
          description: Apply compatibility policy rules and annotate risk.
      sinks:
        - ref: spec.erp.scene-package-metadata-query
          fields:
            - packageCoordinate
            - compatibilityStatus
            - riskLevel
    business_rules:
      - id: rule.package-coordinate-unique
        description: Package coordinate must be unique in registry scope
        entity_ref: package_contract
        bind_to: spec.erp.scene-package-contract-read
        status: enforced
      - id: rule.compatibility-before-publish
        description: Compatibility check must pass before metadata publication
        entity_ref: compatibility_profile
        bind_to: spec.erp.scene-package-compatibility-check
        status: active
    decision_logic:
      - id: decision.compatibility-gate-strategy
        description: Block publication when scene_api_version is incompatible
        bind_to: spec.erp.scene-package-compatibility-check
        status: resolved
        automated: true
      - id: decision.risk-annotation-strategy
        description: Use low/medium/high annotation based on policy violations
        bind_to: spec.erp.scene-package-metadata-query
        status: resolved
        automated: true
