apiVersion: kse.scene/v0.2
kind: scene
metadata:
  obj_id: scene.erp.order-fulfillment-workflow
  obj_version: 0.1.0
  title: ERP Order Fulfillment Workflow
spec:
  domain: erp
  intent:
    goal: Orchestrate reserve payment release and status transition for order fulfillment
  model_scope:
    read:
      - spec.erp.order-fulfillment-eligibility-check
    write:
      - spec.erp.inventory-reserve
      - spec.erp.payment-authorize
      - spec.erp.fulfillment-release
      - spec.erp.order-status-update
  capability_contract:
    bindings:
      - type: query
        ref: spec.erp.order-fulfillment-eligibility-check
        intent: Validate order is ready for fulfillment
        preconditions:
          - order exists
          - order is not cancelled
        postconditions:
          - fulfillment eligibility decision is available
        timeout_ms: 1500
        retry: 1
      - type: invoke
        ref: spec.erp.inventory-reserve
        depends_on: spec.erp.order-fulfillment-eligibility-check
        intent: Reserve inventory for all fulfillable order lines
        preconditions:
          - fulfillment eligibility decision is available
        postconditions:
          - inventory reservation records are created
        timeout_ms: 2500
        retry: 2
      - type: invoke
        ref: spec.erp.payment-authorize
        depends_on: spec.erp.inventory-reserve
        intent: Authorize payment for reserved order amount
        preconditions:
          - inventory reservation records are created
        postconditions:
          - payment authorization status is captured
        timeout_ms: 2500
        retry: 2
      - type: invoke
        ref: spec.erp.fulfillment-release
        depends_on: spec.erp.payment-authorize
        intent: Release order to warehouse fulfillment queue
        preconditions:
          - payment authorization status is captured
        postconditions:
          - fulfillment execution is issued
        timeout_ms: 2500
        retry: 1
      - type: invoke
        ref: spec.erp.order-status-update
        depends_on: spec.erp.fulfillment-release
        intent: Persist order status transition after fulfillment release
        preconditions:
          - fulfillment execution is issued
        postconditions:
          - order status reflects fulfillment progress
        timeout_ms: 1500
        retry: 1
  governance_contract:
    risk_level: medium
    approval:
      required: true
    idempotency:
      required: true
      key: fulfillmentExecutionId
    data_lineage:
      sources:
        - ref: spec.erp.order-fulfillment-eligibility-check
          fields:
            - orderId
            - eligible
            - reasons
      transforms:
        - operation: aggregateFulfillmentExecution
          description: Build execution payload from eligibility reservation and payment states.
        - operation: deriveStatusTransition
          description: Derive status transition from release and payment outcomes.
      sinks:
        - ref: spec.erp.order-status-update
          fields:
            - orderId
            - statusId
            - executionId
